[palettes.colors]
color_fg0 = '#{{ $term0 }}'
color_fg1 = '#{{ $onBackground }}'
color_bg1 = '#{{ $background }}'
color_bg3 = '#{{ $term4 }}'
color_blue = '#{{ $tertiary }}'
color_aqua = '#{{ $term5 }}'
color_green = '#{{ $term2 }}'
color_orange = '#{{ $primary }}'
color_purple = '#{{ $term5 }}'
color_red = '#{{ $term1 }}'
color_yellow = '#{{ $term6 }}'
