[palettes.colors]
color_primary = '#{{ $primary }}'
color_on_primary = '#{{ $onPrimary }}'
color_secondary = '#{{ $secondary }}'
color_on_secondary = '#{{ $onSecondary }}'
color_tertiary = '#{{ $tertiary }}'
color_on_tertiary = '#{{ $onTertiary }}'
color_pri_ctr = '#{{ $primaryContainer }}'
color_on_pri_ctr = '#{{ $onPrimaryContainer }}'
color_sec_ctr = '#{{ $secondaryContainer }}'
color_on_sec_ctr = '#{{ $onSecondaryContainer }}'
color_ter_ctr = '#{{ $tertiaryContainer }}'
color_on_ter_ctr = '#{{ $onTertiaryContainer }}'
color_surface = '#{{ $surface }}'
color_on_surface = '#{{ $onSurface }}'
color_surface_dim = '#{{ $surfaceDim }}'
color_outline = '#{{ $outline }}'
color_error = '#{{ $error }}'
color_on_error = '#{{ $onError }}'
color_error_ctr = '#{{ $errorContainer }}'
color_on_error_ctr = '#{{ $onErrorContainer }}'
color_success = '#{{ $success }}'
color_on_success = '#{{ $onSuccess }}'
